#!/system/bin/sh

###################################Fstrim#######################################
FS_LOGFILE=/data/fstrim.log

echo "fstrim started at $( date +"%m-%d-%Y %H:%M:%S" )" | tee -a $FS_LOGFILE;

busybox fstrim -v /cache | tee -a $FS_LOGFILE;
busybox fstrim -v /data | tee -a $FS_LOGFILE;
busybox fstrim -v /system | tee -a $FS_LOGFILE

echo "fstrim finished at $( date +"%m-%d-%Y %H:%M:%S" )" | tee -a $FS_LOGFILE;

