#!/system/bin/sh

#if your feature is already #'d out, remove the # from the ECHO line. Some of these will be modifiable through a kernel tweaking app
#Some values are disabled, edit this to enabled some features

#Set Wake Gestures: 1 for enabled, 0 for disabled
#echo 1 > /sys/android_touch/wake_gestures

#Set Sweep2wake: use numbers to add exactly what you want, disabled by default
#echo 0 > /sys/android_touch/sweep2wake

#Set Doubletap2wake: 1 for enabled 0 for disabled
#echo 1 > /sys/android_touch/doubletap2wake

#Set Sweep2sleep: 1 for enabled to the right, 2 for left, 3 for both
echo 3 > /sys/android_touch/sweep2sleep

#Set Wake vibration strength number for value
#echo > /sys/android_touch/vib_strength

#Set Pocket Detection: 1 for enabled, 0 for disabled
echo 1 > /sys/android_touch/pocket_detect

#Set Camera Launch
#echo 0 > /sys/android_touch/camera_gesture

#Set FASTCHARGE: 1 for enabled, 0 for disabled
#echo 0 > /sys/kernel/fast_charge/force_fast_charge

#Set fsync: 1 for enabled, 0 for disabled
#echo 0 > /sys/module/sync/parameters/fsync_enabled;

#Set Max screen off: enabled by default
echo 1 > /sys/devices/system/cpu/cpu0/cpufreq/screen_off_max

#cover settings: 1 for disabled, 0 for enabled
echo 1 > /sys/module/hall_sensor/parameters/disable_cover;

#backlight dimmer settings: 1 for dimmer, 2 for dimmest, 0 for disabled
echo 1 > /sys/backlight_dimmer/backlight_dimmer;

exit 0